export const ModuleData = [
    {   
        num: "1.",
        title: "Need to invest",
        body: "Learn about the importance of savings. Identify avenues to invest the savings in suitable investment vehicle. Compare historical returns generated by different assets, and know what to expect"
    }
]